export const REQUEST_COUNTRIES = 'REQUEST_COUNTRIES';
export const RECEIVE_COUNTRIES = 'RECEIVE_COUNTRIES';
export const SEARCH_COUNTRY = 'SEARCH_COUNTRY';
export const REQUEST_DAILY_STATS = 'REQUEST_DAILY_STATS';
export const RECEIVE_DAILY_STATS = 'RECEIVE_DAILY_STATS';
export const REQUEST_WEEK_STATS = 'REQUEST_WEEK_STATS';
export const RECEIVE_WEEK_STATS = 'RECEIVE_WEEK_STATS';
